name: Bug report
description: Report a problem.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug. Feel free to add screenshots or a video.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Explain how to reproduce this issue.
      value: |
        1.
        2.
        3.
        ...
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: What did you expect to happen?
      description: Tell us what should happen when you encounter this bug.
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Copy and paste any relevant logs. This is automatically formatted into code, so no need for backticks.
      render: shell
